name: Tests
on: [push]
jobs:
  bun-tests:
    name: Run Bun tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: ls test/*.test.ts | xargs -I {} sh -c "bun test {} || exit 1"

  deno-tests:
    name: Run Deno tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno install
      - run: |
          deno test -RS --no-check test/lexer.test.ts && \
          deno test -RS --no-check test/parser.test.ts && \
          deno test -RS --no-check test/tags.test.ts && \
          deno test -RS --no-check test/vars.test.ts && \
          deno test -RS --no-check test/util.test.ts && \
          deno test -RS --no-check test/tags-os.test.ts && \
          deno test -RS --no-check test/tags-time.test.ts && \
          deno test -RWS --no-check test/config.test.ts || exit 1
