name: Tests
on: [push]
jobs:
  tests:
    name: Run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: ls test/*.test.ts | xargs -I {} bun test {}
